In [2]:
import pandas as pd

In [125]:
myData = pd.read_csv("hepatitis.csv", sep=',')

In [126]:
myData

class  age  sex  steroid  antivirals  fatigue  malaise  anorexia  \
0        2   30    2        1           2        2        2         2   
1        2   50    1        1           2        1        2         2   
2        2   78    1        2           2        1        2         2   
3        2   34    1        2           2        2        2         2   
4        2   34    1        2           2        2        2         2   
..     ...  ...  ...      ...         ...      ...      ...       ...   
137      1   46    1        2           2        1        1         1   
138      2   44    1        2           2        1        2         2   
139      2   61    1        1           2        1        1         2   
140      2   53    2        1           2        1        2         2   
141      1   43    1        2           2        1        2         2   

     liver_big  liver_firm  spleen_palable  spiders  ascites  varices  \
0            1           2               2        2        2        2   
1            1           2               2        2        2        2   
2            2           2               2        2        2        2   
3            2           2               2        2        2        2   
4            2           2               2        2        2        2   
..         ...         ...             ...      ...      ...      ...   
137          2           1               2        1        1        1   
138          2           1               2        2        2        2   
139          1           2               2        1        2        2   
140          2           2               1        1        2        1   
141          2           2               1        1        1        2   

     bilirubin  alk_phosphate  sgot  albumin  protime  histology  
0          1.0             85    18      4.0       61          1  
1          0.9            135    42      3.5       61          1  
2          0.7             96    32      4.0       61          1  
3          1.0            105   200      4.0       61          1  
4          0.9             95    28      4.0       75          1  
..         ...            ...   ...      ...      ...        ...  
137        7.6            105   242      3.3       50          2  
138        0.9            126   142      4.3       61          2  
139        0.8             75    20      4.1       61          2  
140        1.5             81    19      4.1       48          2  
141        1.2            100    19      3.1       42          2  

[142 rows x 20 columns]

In [127]:
import numpy

In [128]:
myData = numpy.array(myData)

In [129]:
type(myData)

numpy.ndarray

In [130]:
numpy.shape(myData)

(142, 20)

In [131]:
myData

array([[ 2. , 30. ,  2. , ...,  4. , 61. ,  1. ],
       [ 2. , 50. ,  1. , ...,  3.5, 61. ,  1. ],
       [ 2. , 78. ,  1. , ...,  4. , 61. ,  1. ],
       ...,
       [ 2. , 61. ,  1. , ...,  4.1, 61. ,  2. ],
       [ 2. , 53. ,  2. , ...,  4.1, 48. ,  2. ],
       [ 1. , 43. ,  1. , ...,  3.1, 42. ,  2. ]])

In [132]:
totalLive = list(myData[0:, 0]).count(2)

In [133]:
totalDied = list(myData[0:, 0]).count(1)

In [134]:
totalLive

116

In [135]:
totalDied

26

In [136]:
# selecting all rows that contans 2 in class column
# all died
allDied = myData[myData[:, 0] == 1]

In [137]:
numpy.shape(allDied)

(26, 20)

In [138]:
# selecting all rows that contans 2 in class column
# all live
allLive = myData[myData[:, 0] == 2]

In [139]:
numpy.shape(allLive)

(116, 20)

In [140]:
allLive

array([[ 2. , 30. ,  2. , ...,  4. , 61. ,  1. ],
       [ 2. , 50. ,  1. , ...,  3.5, 61. ,  1. ],
       [ 2. , 78. ,  1. , ...,  4. , 61. ,  1. ],
       ...,
       [ 2. , 44. ,  1. , ...,  4.3, 61. ,  2. ],
       [ 2. , 61. ,  1. , ...,  4.1, 61. ,  2. ],
       [ 2. , 53. ,  2. , ...,  4.1, 48. ,  2. ]])

In [141]:
# All died with steriod
list(allDied[:, 3]).count(2)

11

In [142]:
allDied[:, 3]

array([1., 1., 2., 2., 1., 2., 1., 2., 1., 1., 1., 2., 1., 2., 1., 1., 1.,
       2., 1., 1., 1., 2., 1., 2., 2., 2.])

In [143]:
# All died with antiviral
list(allDied[:, 5]).count(2)

2

In [144]:
# All died with fatigue
list(allDied[:, 6]).count(2)

7

In [145]:
# All live with steriod
list(allLive[:, 4]).count(2)

95

In [146]:
# All live with antiviral
list(allLive[:, 5]).count(2)

49

In [147]:
# All live with fatigue
list(allLive[:, 6]).count(2)

81